name: Check Code File Headers

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.py'
      - '**/*.sh'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.R'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**/*.py'
      - '**/*.sh'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.R'

jobs:
  check-headers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full git history for author information
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython
    
    - name: Run header check script
      run: |
        # Find all supported code files and run header check
        find . -type f \( -name "*.py" -o -name "*.sh" -o -name "*.js" -o -name "*.ts" -o -name "*.R" \) -not -path "*/\.*" | xargs python audt_data/utils/check_headers.py
    
    - name: Create Pull Request if headers were added
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add standard headers to code files"
        title: "Add standard headers to code files"
        body: |
          This PR automatically adds standardized headers to code files following the repository guidelines.
          
          The headers include:
          - Project name: augmented urban data triangulation (audt)
          - Repository name
          - File title
          - Description
          - Author information
          
          Please review the changes to ensure headers are correctly formatted.
        branch: auto-headers
        branch-suffix: timestamp
        delete-branch: true
        base: ${{ github.ref_name }}
